// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rosmvxigwcoclamawjps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvc212eGlnd2NvY2xhbWF3anBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5ODU4NTQsImV4cCI6MjA1NDU2MTg1NH0.rhbc7ns0dKio6LmATIbcQ0SFuUq-nFh3ZyOQZ3cr-QA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);